theme = 'diary'
defaultContentLanguage = "en"
canonifyURLs = true
title = 'Jool Site'
languageCode = 'en'

[params]
author = "Jool"
description = "Site made by Jool"
profilePicture = "images/profile.png"
title = "Kerbsite"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "YouTube"
url = "https://www.youtube.com/channel/UCNYA6ENeBhAX--OFFIQWDeQ"

[[params.socialIcons]]
icon = "fab fa-twitch"
title = "Twitch"
url = "https://www.twitch.tv/jool4832"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Jool402"

[[params.socialIcons]]
icon = "fa-thin fa-m"
title = "Matrix"
url = "https://matrix.to/#/@jool4832:matrix.org"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:best_hope342@twilightbunker.maskmy.id"

[services]
  [services.disqus]
    shortname = 'Jool'

[menu]

	[[menu.main]]
	name = "Home"
	identifier = "home"
	weight = 100
	url = "/"

	[[menu.main]]
	name = "Posts"
	weight = 200
	identifier = "posts"
	url = "/posts/"
