theme = 'DoIt'
title = 'KeSite'
baseURL = 'https://jool402.github.io/joolsite/'
defaultContentLanguage = "en"
homeSubtitle = "Welcome to Jool's Blog!"

[params]
enableGlobalLanguageMenu = true

[params.author]
name = "Jool"
github = "Jool402/joolsite"
youtube = "@Jool4832"
email = "dqz8grpl9@mozmail.com"

[languages]
	[languages.en]
	disabled = false
	languageName = "English"
	languageDirection = "ltr"
	weight = 1

	[languages.es]
	disabled = false
	languageName = "Español"
	languageDirection = "ltr"
	weight = 2

	[languages.fr]
	disabled = false
	languageName = "French"
	languageDirection = "ltr"
	weight = 3
[menu]

	[[menu.main]]
	name = "Home"
	identifier = "home"
	weight = 100
	url = "/"
