theme = 'hugo-PaperMod'
title = 'Jool Site'
languageCode = 'en'
baseURL = 'https://example.com/'

[params]
author = "Jool"
description = "Site made by Jool"
profilePicture = "images/profile.png"
title = "Kerbsite"

[services]
  [services.disqus]
    shortname = 'Jool'

[menu]

	[[menu.main]]
	name = "Home"
	identifier = "home"
	weight = 100
	url = "/"

	[[menu.main]]
	name = "Posts"
	weight = 200
	identifier = "posts"
	url = "/posts/"
